name: CI devops 2025

on:
  push:
    branches: [ main, develop ]  # Le robot travaille sur ces branches
  pull_request:                   # Et quand on fait des "pull requests"

jobs:
  test-backend:
    runs-on: ubuntu-24.04         # Le robot utilise un ordinateur Ubuntu
    
    steps:
      # Étape 1 : Télécharger le code
      - uses: actions/checkout@v4  # Comme quand tu télécharges un jeu
      
      # Étape 2 : Installer Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'       # On utilise Java version 21
          distribution: 'temurin'  # C'est une version de Java
      
      # Étape 3 : Tester l'application
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml  # Commande magique pour tester