name: CI devops 2025

on:
  push:
    branches: [ main, develop ]  # Le robot travaille sur ces branches
  pull_request:                   # Et quand on fait des "pull requests"

jobs:
  test-backend:
    runs-on: ubuntu-24.04         # Le robot utilise un ordinateur Ubuntu
    
    steps:
      # Étape 1 : Télécharger le code
      - uses: actions/checkout@v4  # Comme quand tu télécharges un jeu
      
      # Étape 2 : Installer Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'       # On utilise Java version 21
          distribution: 'temurin'  # C'est une version de Java
      
      # Étape 3 : Tester l'application
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml  # Commande magique pour tester

      - name: SonarCloud analysis
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=HmIheb_tp-devops-correction-docker

  build-and-push-docker-image:
    needs: test-backend  # Attend que les tests soient OK
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Connexion à Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      # Créer l'image de l'API
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api  # Où trouver le Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Envoie seulement sur "main"
      
      # Même chose pour la base de données...
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      
      # ...et pour le serveur web
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
  